server:
  port: 8000
  
spring:  
  h2:
    console:
      enabled: true
#      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/Develop/Github/SpringBlogExam/test_db;AUTO_SERVER=TRUE
    url: jdbc:h2:mem:testdb
    username: test
    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: 
---
spring:
  profiles: local
server:
  port: 8080
---
spring:
  profiles: dev
server:
  port: 8090
---
spring:
  profiles: prod
server:
  port: 80